In [2]:
import numpy as np

In [ ]:
# how to get this position where element of two arrays match?

In [3]:
a= np.array([1,2,3,2,3,4,3,4,5,6])
b= np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [11]:
# do check in 2d array

In [12]:
a= np.array([[1,2,3,2,3],[4,3,4,5,6]])
print(a)
b= np.array([[7,2,10,2,7],[4,9,4,9,8]])
print(b)

np.where(a==b)

[[1 2 3 2 3]
 [4 3 4 5 6]]
[[ 7  2 10  2  7]
 [ 4  9  4  9  8]]


(array([0, 0, 1, 1], dtype=int64), array([1, 3, 0, 2], dtype=int64))

In [14]:
a= np.array([[1,2,3,2,3],[4,3,4,5,6]])
print(a)
b= np.array([[7,2,10,2,7],[4,9,4,9,8]])
print(b)

np.where(a==b,a,b)

[[1 2 3 2 3]
 [4 3 4 5 6]]
[[ 7  2 10  2  7]
 [ 4  9  4  9  8]]


array([[ 7,  2, 10,  2,  7],
       [ 4,  9,  4,  9,  8]])

In [21]:
# Check this arr present or not 

In [19]:
arr= np.array([[1,2,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15],
             [16,17,18,19,20]])
arr.tolist()
[1,2,3,4,5] in arr

True

In [20]:
arr= np.array([[1,2,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15],
             [16,17,18,19,20]])
arr.tolist()
[21,22,23,24,25] in arr

False

In [26]:
print([1,2,3,4,5]in arr.tolist())
print([16,17,20,19,18]in arr.tolist())
print([3,2,5,-4,5]in arr.tolist())
print([11,12,13,14,15]in arr.tolist())

True
False
False
True


In [29]:
arr = np.array([[2,8,9,4],
               [9,4,9,4],
               [4,5,9,7],
               [2,9,4,3]])
output = repr(arr).count("9, 4")
print(output)

4


In [31]:
a= np.array([1,0,np.nan,np.inf])
print("original array")
print(a)
print("test element-wise for nam : ")
print(np.isnan(a))

original array
[ 1.  0. nan inf]
test element-wise for nam : 
[False False  True False]


In [34]:
x= np.array([1,2,3,4])
print("Original Array:")
print(x)
print("test if none of the element of the said array is zero :")
print(np.all(x))
x=np.array([0,1,2,3])
print("original array:")
print(x)
print("test if none of the element of the said array is zero :")
print(np.all(x))

Original Array:
[1 2 3 4]
test if none of the element of the said array is zero :
True
original array:
[0 1 2 3]
test if none of the element of the said array is zero :
False


In [35]:
# use "any" keyword 

In [36]:
x= np.array([1,2,3,4])
print("Original Array:")
print(x)
print("test if none of the element of the said array is zero :")
print(np.any(x))
x=np.array([0,1,2,3])
print("original array:")
print(x)
print("test if none of the element of the said array is zero :")
print(np.any(x))

Original Array:
[1 2 3 4]
test if none of the element of the said array is zero :
True
original array:
[0 1 2 3]
test if none of the element of the said array is zero :
True


In [ ]:
l= [12,23,13,100,36.32]
print("original List :",l)
np.array


In [37]:
x= np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6]=11
print(x)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [39]:
x= np.random.random((5,5))
print("Original array")
print(x)
xmin,xmax=x.min(), x.max()
print("\n")
print("minimum and maximum values:")
print(xmin,xmax)

Original array
[[0.5188303  0.86097358 0.50965405 0.46932492 0.14496172]
 [0.61348318 0.55408273 0.08898783 0.76895787 0.80277021]
 [0.75589941 0.99272076 0.85793001 0.60351531 0.61860838]
 [0.92142883 0.01742653 0.13088574 0.00582375 0.51705939]
 [0.28603706 0.80532697 0.47279303 0.02943912 0.54149777]]


minimum and maximum values:
0.005823751574904001 0.9927207624423248


In [41]:
p=[[1,0],[0,1]]
q=[[1,2],[3,4]]
print("Oringinal matrix :")
print(p)
print(q)
result = np.dot(p,q)
print("\n")
print("result of the said matrix multplication :")
print(result)

Oringinal matrix :
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]


result of the said matrix multplication :
[[1 2]
 [3 4]]


In [42]:
p=[[3,4],[5,6]]
q=[[9,16],[17,18]]
print("Oringinal matrix :")
print(p)
print(q)
result = np.dot(p,q)
print("\n")
print("result of the said matrix multplication :")
print(result)

Oringinal matrix :
[[3, 4], [5, 6]]
[[9, 16], [17, 18]]


result of the said matrix multplication :
[[ 95 120]
 [147 188]]


In [44]:
arr1 = np.diagflat([[1,2],[3,4]])
print(arr1)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [46]:
m=np.arange(6).reshape(3,2)
print("original matrix")
print(m)

result = np.trace(m)
print("\n")
print("condition number of the said matrix :")
print(result)

original matrix
[[0 1]
 [2 3]
 [4 5]]


condition number of the said matrix :
3


In [47]:
m=np.arange(1,18,2).reshape(3,3)
print("original matrix")
print(m)

result = np.trace(m)
print("\n")
print("condition number of the said matrix :")
print(result)

original matrix
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


condition number of the said matrix :
27


In [49]:
m=np.arange(1,13).reshape(3,4)
ma=m**2
print("original matrix")
print(ma)

result = np.trace(ma)
print("\n")
print("condition number of the said matrix :")
print(result)

original matrix
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


condition number of the said matrix :
158


In [51]:
a= np.arange(24).reshape((2,3,2,2))
print(a)
print("\n")
np.trace(a)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]




array([[16, 18],
       [20, 22]])

In [54]:
a =np.arange(8).reshape((2,2,2))
print(a)
print('\n')
np.trace(a)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]




array([6, 8])

In [55]:
arr =np.array([12.202,90.23120,123.020,23.202])
print("pinting the original array values : ",end="")
print(arr)
print("\n")
print("array values rounded off to 2 decimal postion ",np.around(arr,2))
print("array values rounded off to -1 decimal postion ",np.around(arr,-1))

pinting the original array values : [ 12.202   90.2312 123.02    23.202 ]


array values rounded off to 2 decimal postion  [ 12.2   90.23 123.02  23.2 ]
array values rounded off to -1 decimal postion  [ 10.  90. 120.  20.]
