In [2]:
import numpy as np

In [3]:
num=[1,2,3,]
a1 = np.array(num)
print(a1)

[1 2 3]


In [4]:
num2= [[2,2,3,4],[4,5,6,7]]
a2 = np.array(num2)
print(a2)

[[2 2 3 4]
 [4 5 6 7]]


In [10]:
num3 = [[[1,2,3],[4,5,6],[7,8,9]]]
a3=np.array(num3)
print(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [12]:
print(a3.dtype)

int32


In [14]:
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [15]:
arr1 = np.zeros(5,dtype=int)
print(arr1)

[0 0 0 0 0]


In [16]:
arr2 = np.zeros((2,3))
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
arr2 = np.zeros((2,3),dtype=int)
print(arr2)

[[0 0 0]
 [0 0 0]]


In [22]:
arr2 = np.ones((2,3),dtype=int)
print(arr2)

[[1 1 1]
 [1 1 1]]


In [33]:
arr3 = np.full(6,5)
print(arr3)

[5 5 5 5 5 5]


In [28]:
arr4 = np.eye(4)
print(arr4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [29]:
arr4 = np.eye(4, dtype = int)
print(arr4)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [35]:
arr5 = np.eye(8, dtype = int)
print(arr5)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


In [36]:
arr6=np.diag([1,2,3,4])
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [38]:
rand_arr = np.random.randint(1,15,4)
print(rand_arr)

[ 7 14  5 10]


In [39]:
rand_arr = np.random.randint(1,15,(4,4))
print(rand_arr)

[[12  9 13  1]
 [ 9 10 14 13]
 [ 5  9  8  8]
 [ 1 11  3  8]]


In [40]:
rand_arr = np.random.randint(500,1000,10)
print(rand_arr)

[863 718 701 502 709 513 870 791 652 939]


In [42]:
np.random.seed(123)
rand_arr1 = np.random.randint(1,100,20)
print(rand_arr1)

[67 93 99 18 84 58 87 98 97 48 74 33 47 97 26 84 79 37 97 81]


In [43]:
num= np.array([5,15,25,35])
print(num[0])
print(num[3])

5
35


In [45]:
num= np.array([5,15,25,35])
print(num[-4])
print(num[-3])

5
15


In [46]:
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [48]:
arr = np.arange(0,24).reshape(6,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [49]:
arr = np.arange(0,24).reshape(12,2)
print(arr)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [50]:
arr = np.arange(0,4).reshape(2,2)
print(arr)

[[0 1]
 [2 3]]


In [51]:
a= np.random.rand()
print(a)

0.7379954057320357


In [52]:
num = np.array([5,15,25,35])
print(num.size)

4


In [56]:
a=np.array([1,20,3.6,4,5,100])
print(a)

[  1.   20.    3.6   4.    5.  100. ]


In [54]:
a=np.array(['C',20,3,4,5,100])
print(a)

['C' '20' '3' '4' '5' '100']


In [58]:
num_line = np.linspace(0,1,20)
print(num_line)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [59]:
num_arr=np.array([[5,6,2],[9,8,1]])
print(np.sort(num_arr))

[[2 5 6]
 [1 8 9]]
